# Generated by Django 3.2.5 on 2021-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20210727_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='status',
            field=models.CharField(choices=[('o', 'on sale'), ('p', 'purchased')], default='on line', max_length=15),
        ),
    ]
