# Generated by Django 3.2.5 on 2021-07-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_alter_bond_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='status',
            field=models.CharField(choices=[('o', 'on sale'), ('p', 'purchased')], default='o', max_length=1),
        ),
    ]
